### ISSUE TITLE
[Git hakodate] Fails to compile with Rust 1.72.0

### ISSUE THREAD

**Issue by hartwork** [idobata/hokaido#8]
```console
# rustc --version
rustc 1.72.0 (5680fa18f 2023-08-23)

# git rev-parse HEAD 
817f65dc9a95e6e0c83a1a8c4a0e277ff069b4f7

# cargo build
   Compiling pty-shell v0.1.4
   Compiling rmp-serialize v0.8.1
   Compiling env_logger v0.3.5
   Compiling docopt v0.6.86
error[E0276]: impl has stricter requirements than trait
  --> /home/user123/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pty-shell-0.1.4/src/lib.rs:50:30
   |
38 |     fn proxy<H: PtyHandler>(&self, handler: H) -> Result<()>;
   |     --------------------------------------------------------- definition of `proxy` from trait
...
50 |     fn proxy<H: PtyHandler + 'static>(&self, handler: H) -> Result<()> {
   |                              ^^^^^^^ impl has extra requirement `H: 'static`

For more information about this error, try `rustc --explain E0276`.
error: could not compile `pty-shell` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

CC #6

**Comment by hartwork** [comment]
Closing to keep my https://github.com/issues clean…
